"""empty message

Revision ID: fed1a4308312
Revises: 
Create Date: 2021-01-29 23:41:19.703022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fed1a4308312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owing_data')
    op.drop_table('payments_data')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('registered_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('logins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments_data',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['users.id'], name='payments_data_user_from_fkey'),
    sa.ForeignKeyConstraint(['user_to'], ['users.id'], name='payments_data_user_to_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', name='payments_data_pkey')
    )
    op.create_table('owing_data',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_from', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('made_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['users.id'], name='owing_data_user_from_fkey'),
    sa.ForeignKeyConstraint(['user_to'], ['users.id'], name='owing_data_user_to_fkey'),
    sa.PrimaryKeyConstraint('id', name='owing_data_pkey')
    )
    # ### end Alembic commands ###
