# base image
FROM python:3.8-slim

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
WORKDIR /usr/src


# add app
COPY . /usr/src

#install requirements
RUN pip install -r requirements.txt

# run server
CMD gunicorn --workers=2 --threads=5 wsgi:flask_app -b 0.0.0.0:5000 